@startuml C4_Elements
!include https://raw.githubusercontent.com/jacobduijzer/BestBeforeAzure/main/documentation/assets/vars.puml
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Container.puml
!define AzurePuml https://raw.githubusercontent.com/RicardoNiepel/Azure-PlantUML/master/dist
!includeurl AzurePuml/AzureCommon.puml
!includeurl AzurePuml/AzureC4Integration.puml
!includeurl AzurePuml/Compute/AzureFunction.puml
!includeurl AzurePuml/Databases/all.puml
!includeurl AzurePuml/DevOps/AzureRepos.puml
!includeurl AzurePuml/DevOps/AzurePipelines.puml
!includeurl AzurePuml/Management/AzureResourceGroups.puml
!includeurl AzurePuml/Containers/AzureWebAppForContainers.puml


Person(personAlias, personName, personDesc)

System_Boundary(application, applicationName) {

    AzureWebAppForContainers(webService, "Web Application", "WebApp for Containers", "Frontend to manage products and stock")

    AzureCosmosDb(cosmosDbAlias, "Products & Stock Database", "SQL Api")

    AzureFunction(functionTrigger, "Stock Updates", "Timed Trigger")

    Rel_L(functionTrigger, cosmosDbAlias, "Checks stock")
}

System_Ext(emailSystemAlias, emailSystemName, emailSystemDesc)

Rel(personAlias, webService, "Adds products to stock, manages stock")
Rel(webService, cosmosDbAlias, "Storing products and stock")
Rel_R(functionTrigger, emailSystemAlias, "Sends stock updates")

@enduml