@startuml C4_Elements

!include https://raw.githubusercontent.com/jacobduijzer/BestBeforeAzure/main/documentation/vars.puml
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Component.puml
!define AzurePuml https://raw.githubusercontent.com/RicardoNiepel/Azure-PlantUML/master/dist
!includeurl AzurePuml/AzureCommon.puml
!includeurl AzurePuml/Compute/AzureFunction.puml
!includeurl AzurePuml/Databases/all.puml

AzureFunction(functionTrigger, "Stock Updates", "Timed Trigger")
Component(getProductsQuery, "GetProductsQuery", "GetProducts Query Handler", "Gets products with stock")
Component(productsService, "ProductsService", "Products Service", "The authentication logic")
AzureCosmosDb(cosmosDbAlias, "Products & Stock Database", "SQL Api")

Rel_Back(functionTrigger, getProductsQuery, "Delivers")
Rel_Back(getProductsQuery, productsService, "Delivers")
Rel_Back(productsService, cosmosDbAlias, "Delivers")

System_Ext(emailSystemAlias, emailSystemName, emailSystemDesc
Rel(functionTrigger, emailSystemAlias, "Uses")

@enduml