@startuml C4_Elements
!include https://raw.githubusercontent.com/jacobduijzer/BestBeforeAzure/main/documentation/vars.puml
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Context.puml

Person(personAlias, personName, personDesc)

System(systemAlias, applicationName, "Application to manage stock and products")
System_Ext(emailSystemAlias, "Email System", "Sends emails with stock updates to users")

Rel(personAlias, systemAlias, "Adds products to stock, manages stock")
Rel_R(systemAlias, emailSystemAlias, "sends emails using")
@enduml